"""Synth Containers Trace V5 — the local, portable execution-record authority.

Consumers import from ``synth_containers.tracing``; nothing should reach into a
consumer-specific helper for a trace fact.

Authority boundaries this package enforces:

- ``TraceDocumentV5`` and sealed capture segments own execution facts.
- ``TraceEvidenceBundleV5`` owns append-only derived evidence and never mutates a trace.
- V4, ``experiments.trace.v4``, and Codex JSONL are imports or projections, never a
  second authority.
- Traces describe executions; they do not own task, job, evaluation-attempt, or
  research-study lifecycle.
- Push 1 is local-only: filesystem bodies plus a SQLite-compatible catalog. The store
  interfaces exist so Stage 2 can add implementations without changing trace identity.
"""

from .canonical import (
    CANONICAL_JSON_PROFILE,
    DIGEST_ALGORITHM,
    bytes_digest,
    canonical_bytes,
    canonical_text,
    content_digest,
    readable_json,
    record_id,
    seal_record,
    text_digest,
    utc_now,
)
from .capture import (
    BindingCaptureV1,
    BindingContainerV1,
    BindingContextV1,
    BindingWorkloadV1,
    CaptureCoverageReceiptV1,
    CaptureMode,
    CaptureNotReady,
    CapturePolicyV1,
    CaptureProxy,
    CaptureScope,
    CaptureSession,
    CaptureSupervisor,
    Interception,
    LocalCollector,
    RawCaptureEnvelopeV1,
    RawRecordType,
    RawSpool,
    SealedCapture,
    SupervisorConfig,
    TraceCaptureBindingV1,
    TraceFinalizer,
    TraceSegmentManifestV1,
    WorkloadKind,
    mint_binding,
    repair,
)
from .models import (
    TRACE_SCHEMA_VERSION,
    ActorKind,
    ActorV5,
    AliasNamespace,
    AliasV1,
    AnnotationV1,
    ArtifactRefV5,
    ArtifactRole,
    BenchmarkVerdictV1,
    CriterionDefinitionV1,
    CriterionResultV1,
    CriterionRole,
    EvaluationResultV1,
    EventType,
    EventV5,
    ExecutionStatus,
    GroundingStatus,
    MessageNodeV5,
    MessagePartV5,
    ProducerRefV1,
    ProjectionManifestV1,
    ReceiptV1,
    RewardAggregationV1,
    RewardDefinitionV1,
    RewardEmission,
    RewardRecordV1,
    RewardSourceKind,
    RubricAggregationV1,
    RubricDefinitionV2,
    SelectorKind,
    SessionV5,
    SpanKind,
    SpanV5,
    TraceAnnotatorDefinitionV1,
    TraceCompletenessV5,
    TraceContextV1,
    TraceDocumentV5,
    TraceEvidenceBundleV5,
    TraceIdentityV5,
    TraceKind,
    TraceProvenanceV5,
    TraceRefV5,
    TraceSelectorV1,
    TraceStatus,
    UsageProvenance,
    UsageV5,
    VerificationStatus,
    VerifierDefinitionV1,
    VerifierKind,
    VerifierResultV2,
    aggregate_rubric_score,
    resolve_selector,
    selector_for,
)
from .projections import load_bundle, project_v4, summarize
from .store import (
    BlobStore,
    CatalogStore,
    FilesystemBlobStore,
    LocalTraceBundle,
    SqliteCatalogStore,
    TraceStore,
    rebuild_catalog,
)
from .validation import (
    ValidationReceiptV1,
    all_schemas,
    json_schema,
    rehydrate_trace,
    validate,
)

__all__ = [
    "CANONICAL_JSON_PROFILE",
    "DIGEST_ALGORITHM",
    "TRACE_SCHEMA_VERSION",
    "ActorKind",
    "ActorV5",
    "AliasNamespace",
    "AliasV1",
    "AnnotationV1",
    "ArtifactRefV5",
    "ArtifactRole",
    "BenchmarkVerdictV1",
    "BindingCaptureV1",
    "BindingContainerV1",
    "BindingContextV1",
    "BindingWorkloadV1",
    "BlobStore",
    "CaptureCoverageReceiptV1",
    "CaptureMode",
    "CaptureNotReady",
    "CapturePolicyV1",
    "CaptureProxy",
    "CaptureScope",
    "CaptureSession",
    "CaptureSupervisor",
    "CatalogStore",
    "CriterionDefinitionV1",
    "CriterionResultV1",
    "CriterionRole",
    "EvaluationResultV1",
    "EventType",
    "EventV5",
    "ExecutionStatus",
    "FilesystemBlobStore",
    "GroundingStatus",
    "Interception",
    "LocalCollector",
    "LocalTraceBundle",
    "MessageNodeV5",
    "MessagePartV5",
    "ProducerRefV1",
    "ProjectionManifestV1",
    "RawCaptureEnvelopeV1",
    "RawRecordType",
    "RawSpool",
    "ReceiptV1",
    "RewardAggregationV1",
    "RewardDefinitionV1",
    "RewardEmission",
    "RewardRecordV1",
    "RewardSourceKind",
    "RubricAggregationV1",
    "RubricDefinitionV2",
    "SealedCapture",
    "SelectorKind",
    "SessionV5",
    "SpanKind",
    "SpanV5",
    "SqliteCatalogStore",
    "SupervisorConfig",
    "TraceAnnotatorDefinitionV1",
    "TraceCaptureBindingV1",
    "TraceCompletenessV5",
    "TraceContextV1",
    "TraceDocumentV5",
    "TraceEvidenceBundleV5",
    "TraceFinalizer",
    "TraceIdentityV5",
    "TraceKind",
    "TraceProvenanceV5",
    "TraceRefV5",
    "TraceSegmentManifestV1",
    "TraceSelectorV1",
    "TraceStatus",
    "TraceStore",
    "UsageProvenance",
    "UsageV5",
    "ValidationReceiptV1",
    "VerificationStatus",
    "VerifierDefinitionV1",
    "VerifierKind",
    "VerifierResultV2",
    "WorkloadKind",
    "aggregate_rubric_score",
    "all_schemas",
    "bytes_digest",
    "canonical_bytes",
    "canonical_text",
    "content_digest",
    "json_schema",
    "load_bundle",
    "mint_binding",
    "project_v4",
    "readable_json",
    "rebuild_catalog",
    "record_id",
    "rehydrate_trace",
    "repair",
    "resolve_selector",
    "seal_record",
    "selector_for",
    "summarize",
    "text_digest",
    "utc_now",
    "validate",
]
