"""Run one annotator as a bounded Codex app-server task.

Protocol: JSON-RPC 2.0 over newline-delimited JSON on the app server's stdio
(``codex app-server``). The runner:

1. ``initialize`` with ``experimentalApi`` so dynamic tools are available;
2. ``thread/start`` in the read-only workspace with ``approvalPolicy: never``,
   ``sandbox: read-only``, an ephemeral thread, and the trace-inspection tools
   registered as *dynamic tools* (served back to Codex by this process);
3. ``turn/start`` with the sealed instructions as the only input and the
   proposal JSON Schema as ``outputSchema``;
4. answers every ``item/tool/call`` by dispatching to ``TraceInspectionTools``,
   declines every approval request, and interrupts the turn on any limit;
5. takes the final ``agentMessage`` text as the proposal.

Hidden reasoning is never requested: reasoning deltas are ignored and never
persisted. Only the structured output, tool calls, and token usage survive.

``AppServerTransport`` is a small protocol so the same runner logic runs
against a scripted in-process fake in tests without a Codex binary.
"""

from __future__ import annotations

import json
import os
import queue
import shutil
import subprocess
import tempfile
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterator, Protocol

from ..canonical import utc_now
from ..models.standards import ProducerKind
from .definitions import RunnerKind
from .execution_trace import ExecutionCapture
from .jobs import RUNNER_VERSION, AnnotationJobErrorCode, AnnotationJobErrorV1, AnnotationJobUsageV1
from .pricing import COST_STATUS_UNAVAILABLE, ModelPrice, PriceTable
from .proposal import STRICT_PROPOSAL_JSON_SCHEMA, normalize_strict_proposal
from .tools import ToolArgumentError, ToolLimitExceeded
from .validation import producer_for

CLIENT_NAME = "synth-containers-annotation"
CLIENT_VERSION = RUNNER_VERSION
DECLINE_TEXT = "annotation tasks are read-only; no commands, file changes, or extra permissions"


class TransportClosed(RuntimeError):
    """The app server went away before the turn completed."""


class AppServerTransport(Protocol):
    """Minimal message pump over one app-server connection."""

    def start(self) -> None: ...

    def send(self, message: dict[str, Any]) -> None: ...

    def receive(self, timeout: float) -> dict[str, Any] | None:
        """Next message from the server, or ``None`` on timeout. Raises TransportClosed."""
        ...

    def close(self) -> None: ...


def minimal_codex_config(*, model: str | None, reasoning_effort: str | None) -> str:
    """The whole configuration an annotator process is allowed to see."""

    lines = [
        "# generated by synth_containers.tracing.annotation; host config is never copied",
        'approval_policy = "never"',
        'sandbox_mode = "read-only"',
    ]
    if model:
        lines.append(f'model = "{model}"')
    if reasoning_effort:
        lines.append(f'model_reasoning_effort = "{reasoning_effort}"')
    lines.append("")
    lines.append("[mcp_servers]")
    return "\n".join(lines) + "\n"


def _kill_process_group(process: subprocess.Popen[bytes], *, wrapper_exited: bool = False) -> None:
    """Terminate everything the app-server wrapper spawned (its own session)."""

    if os.name == "nt":
        if not wrapper_exited:
            process.kill()
        return
    import signal

    pgid = process.pid  # start_new_session=True makes the wrapper the session/group leader
    for sig in (signal.SIGTERM, signal.SIGKILL):
        try:
            os.killpg(pgid, sig)
        except (ProcessLookupError, PermissionError):
            return
        deadline = time.monotonic() + 3
        while time.monotonic() < deadline:
            if not wrapper_exited:
                try:
                    process.wait(timeout=0.05)
                except subprocess.TimeoutExpired:
                    pass
            try:
                os.killpg(pgid, 0)
            except ProcessLookupError:
                return
            time.sleep(0.05)


@dataclass
class StdioAppServerTransport:
    """``codex app-server`` as a child process speaking JSONL on stdio."""

    command: tuple[str, ...] = ("codex", "app-server")
    cwd: Path | None = None
    env: dict[str, str] | None = None
    isolate_codex_home: bool = True
    model: str | None = None
    reasoning_effort: str | None = None
    process: subprocess.Popen[bytes] | None = None
    _queue: "queue.Queue[dict[str, Any] | None]" = field(default_factory=queue.Queue)
    _reader: threading.Thread | None = None
    _stderr: threading.Thread | None = None
    _stderr_tail: list[str] = field(default_factory=list)
    _home: tempfile.TemporaryDirectory[str] | None = None

    def start(self) -> None:
        env = dict(os.environ if self.env is None else self.env)
        if self.isolate_codex_home:
            self._home = tempfile.TemporaryDirectory(prefix="synth-annotation-codex-home-")
            source_home = Path(env.get("CODEX_HOME") or Path.home() / ".codex")
            target_home = Path(self._home.name)
            auth = source_home / "auth.json"
            if auth.exists():
                shutil.copy2(auth, target_home / "auth.json")
                (target_home / "auth.json").chmod(0o600)
            # A generated, minimal config: no host MCP servers, plugins, skills,
            # or trust settings leak into the annotator. The only tools it gets
            # are the dynamic trace tools registered on thread/start.
            (target_home / "config.toml").write_text(
                minimal_codex_config(model=self.model, reasoning_effort=self.reasoning_effort),
                encoding="utf-8",
            )
            (target_home / "config.toml").chmod(0o600)
            env["CODEX_HOME"] = str(target_home)
            for key in list(env):
                if key.startswith(("OPENAI_", "AZURE_OPENAI_")):
                    env.pop(key, None)
        self.process = subprocess.Popen(
            list(self.command),
            cwd=str(self.cwd) if self.cwd else None,
            env=env,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            # Own process group: ``codex app-server`` is a node wrapper around a
            # native binary, and killing only the wrapper orphans the binary.
            start_new_session=(os.name != "nt"),
        )
        self._reader = threading.Thread(target=self._pump, name="codex-app-server-stdout", daemon=True)
        self._reader.start()
        self._stderr = threading.Thread(target=self._drain_stderr, name="codex-app-server-stderr", daemon=True)
        self._stderr.start()

    def _pump(self) -> None:
        assert self.process is not None and self.process.stdout is not None
        for raw in self.process.stdout:
            line = raw.strip()
            if not line:
                continue
            try:
                message = json.loads(line)
            except ValueError:
                continue
            if isinstance(message, dict):
                self._queue.put(message)
        self._queue.put(None)

    def _drain_stderr(self) -> None:
        assert self.process is not None and self.process.stderr is not None
        for raw in self.process.stderr:
            text = raw.decode("utf-8", "replace").rstrip()
            self._stderr_tail.append(text)
            if len(self._stderr_tail) > 200:
                del self._stderr_tail[:-200]

    def send(self, message: dict[str, Any]) -> None:
        if self.process is None or self.process.stdin is None:
            raise TransportClosed("app server is not running")
        try:
            self.process.stdin.write((json.dumps(message, separators=(",", ":")) + "\n").encode("utf-8"))
            self.process.stdin.flush()
        except (BrokenPipeError, OSError) as error:
            raise TransportClosed(f"app server stdin closed: {error}") from error

    def receive(self, timeout: float) -> dict[str, Any] | None:
        try:
            item = self._queue.get(timeout=max(0.0, timeout))
        except queue.Empty:
            return None
        if item is None:
            raise TransportClosed("app server closed its stdout: " + " | ".join(self._stderr_tail[-5:]))
        return item

    def close(self) -> None:
        if self.process is not None:
            try:
                if self.process.stdin is not None:
                    self.process.stdin.close()
            except OSError:
                pass
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                _kill_process_group(self.process)
            else:
                _kill_process_group(self.process, wrapper_exited=True)
        if self._home is not None:
            self._home.cleanup()
            self._home = None


@dataclass
class _TurnState:
    thread_id: str | None = None
    turn_id: str | None = None
    turn_status: str | None = None
    turn_error: str | None = None
    final_text: str | None = None
    usage: AnnotationJobUsageV1 = field(default_factory=AnnotationJobUsageV1)
    events: list[dict[str, Any]] = field(default_factory=list)
    limit_error: AnnotationJobErrorV1 | None = None
    server_errors: list[str] = field(default_factory=list)


class CodexAppServerRunner:
    """``AnnotatorRunner`` that drives one app-server turn per job."""

    kind = RunnerKind.CODEX_APP_SERVER.value
    version = "codex_app_server@2"

    def __init__(
        self,
        transport_factory: Callable[[Path], AppServerTransport] | None = None,
        *,
        command: tuple[str, ...] = ("codex", "app-server"),
        default_model: str | None = None,
        default_effort: str | None = None,
        poll_seconds: float = 0.25,
        usd_per_million_tokens: float | None = None,
        codex_version: str | None = None,
        proxy_enforces_reservation: bool = False,
        price_table: PriceTable | None = None,
    ) -> None:
        self._factory = transport_factory or (
            lambda cwd, model=None, effort=None: StdioAppServerTransport(
                command=command, cwd=cwd, model=model, reasoning_effort=effort
            )
        )
        self._factory_takes_model = transport_factory is None
        self.default_model = default_model
        self.default_effort = default_effort
        self.poll_seconds = poll_seconds
        # Legacy flat price: a cost ceiling is enforceable only as a token
        # ceiling and no USD is reported. The per-model price table supersedes
        # it for any model it prices: billable tokens *and* dollars are bounded
        # mid-turn and ``cost_usd`` is reported as ``pinned_price``.
        self.usd_per_million_tokens = usd_per_million_tokens
        self.price_table = price_table
        # Fail closed: a paid job runs only if dollars are enforced somewhere —
        # either here through a price, or by the host's provider proxy, which
        # the host must assert explicitly when it constructs this runner.
        self.proxy_enforces_reservation = proxy_enforces_reservation
        if codex_version:
            self.version = f"codex_app_server@2+codex{codex_version}"

    def resolve_model(self, requested: str | None, definition_model: str | None) -> str | None:
        return requested or definition_model or self.default_model

    def resolve_effort(self, requested: str | None, program_default: str | None) -> str | None:
        return requested or program_default or self.default_effort

    def price_for(self, model: str | None) -> ModelPrice | None:
        return self.price_table.get(model) if self.price_table is not None else None

    def cost_enforcement(self, model: str | None = None) -> str | None:
        """How the reservation cap is enforced for ``model``, or ``None`` (paid jobs refused)."""

        if self.price_for(model) is not None or self.usd_per_million_tokens:
            return "pinned_price"
        if self.proxy_enforces_reservation:
            return "provider_proxy"
        return None

    def token_ceiling(self, limits: Any, model: str | None = None) -> int | None:
        """Billable-token ceiling: the declared token cap, tightened by the cost cap at the dearest priced rate."""

        ceiling = limits.max_total_tokens
        by_cost: int | None = None
        if limits.max_cost_usd is not None:
            price = self.price_for(model)
            if price is not None:
                by_cost = price.billable_token_ceiling(limits.max_cost_usd)
            elif self.usd_per_million_tokens:
                by_cost = int(limits.max_cost_usd / self.usd_per_million_tokens * 1_000_000)
        if by_cost is not None:
            ceiling = by_cost if ceiling is None else min(ceiling, by_cost)
        return ceiling

    # -- runner ---------------------------------------------------------------------

    def run(self, context: Any) -> Any:
        from .service import RunOutcome  # local import to avoid a cycle

        job = context.job
        tools = context.tools
        limits = job.request.limits
        started = utc_now()
        clock = time.monotonic()
        deadline = clock + float(limits.timeout_seconds)
        state = _TurnState()
        model = job.request.model or self.default_model
        effort = job.request.reasoning_effort or self.default_effort
        token_ceiling = self.token_ceiling(limits, model)
        price = self.price_for(model)
        transport = (
            self._factory(context.workspace_dir, model, effort)
            if self._factory_takes_model
            else self._factory(context.workspace_dir)
        )
        next_id = 0
        pending: dict[int, str] = {}
        error: AnnotationJobErrorV1 | None = None

        def record(kind: str, **detail: Any) -> None:
            if len(state.events) < 2000:
                state.events.append({"at": utc_now(), "kind": kind, **detail})

        def remaining() -> float:
            return deadline - time.monotonic()

        def handle_server_request(message: dict[str, Any]) -> None:
            method = str(message.get("method") or "")
            params = message.get("params") or {}
            request_id = message.get("id")
            if method == "item/tool/call":
                tool = str(params.get("tool") or "")
                arguments = params.get("arguments") or {}
                if not isinstance(arguments, dict):
                    arguments = {"value": arguments}
                try:
                    payload = tools.call(tool, arguments)
                    text = json.dumps(payload, ensure_ascii=False, sort_keys=True)
                    transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"contentItems": [{"type": "inputText", "text": text}], "success": True}})
                    record("tool_call", tool=tool, ok=True, bytes=len(text))
                except ToolLimitExceeded as limit:
                    state.limit_error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.TOOL_LIMIT_EXCEEDED, message=str(limit), detail={"limit": limit.code})
                    transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"contentItems": [{"type": "inputText", "text": f"limit exceeded: {limit}"}], "success": False}})
                    record("tool_call", tool=tool, ok=False, error=limit.code)
                    interrupt()
                except ToolArgumentError as bad:
                    transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"contentItems": [{"type": "inputText", "text": f"invalid arguments: {bad}"}], "success": False}})
                    record("tool_call", tool=tool, ok=False, error="bad_arguments")
                return
            if method in {"item/commandExecution/requestApproval", "item/fileChange/requestApproval"}:
                transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"decision": "decline"}})
                record("approval_declined", method=method)
                return
            if method in {"execCommandApproval", "applyPatchApproval"}:
                transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"decision": "denied"}})
                record("approval_declined", method=method)
                return
            if method == "item/permissions/requestApproval":
                transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"permissions": {}, "scope": "turn"}})
                record("approval_declined", method=method)
                return
            if method == "item/tool/requestUserInput":
                transport.send({"jsonrpc": "2.0", "id": request_id, "result": {"answers": {}}})
                record("user_input_declined", method=method)
                return
            transport.send({"jsonrpc": "2.0", "id": request_id, "error": {"code": -32601, "message": f"{DECLINE_TEXT}: {method}"}})
            record("server_request_refused", method=method)

        def handle_notification(message: dict[str, Any]) -> None:
            method = str(message.get("method") or "")
            params = message.get("params") or {}
            if method == "item/completed":
                item = params.get("item") or {}
                if item.get("type") == "agentMessage" and params.get("turnId") in {None, state.turn_id}:
                    state.final_text = str(item.get("text") or "")
                    record("agent_message", chars=len(state.final_text))
                elif item.get("type") in {"commandExecution", "fileChange"}:
                    record("disallowed_item", item_type=item.get("type"))
                return
            if method == "thread/tokenUsage/updated":
                usage = (params.get("tokenUsage") or {}).get("total") or {}
                total = usage.get("totalTokens")
                # The ceiling bounds *billable* tokens: cached prompt tokens are re-sent
                # every turn and would otherwise dominate the count at a fraction of the cost.
                billable = None
                if isinstance(usage.get("inputTokens"), int):
                    billable = usage["inputTokens"] - int(usage.get("cachedInputTokens") or 0) + int(usage.get("outputTokens") or 0)
                cost_usd: float | None = None
                cost_status = COST_STATUS_UNAVAILABLE
                if price is not None and isinstance(usage.get("inputTokens"), int):
                    cost_usd, cost_status = self.price_table.cost(  # type: ignore[union-attr]
                        model,
                        input_tokens=usage.get("inputTokens"),
                        output_tokens=usage.get("outputTokens"),
                        cached_input_tokens=usage.get("cachedInputTokens"),
                    )
                state.usage = AnnotationJobUsageV1(
                    input_tokens=usage.get("inputTokens"),
                    output_tokens=usage.get("outputTokens"),
                    cached_input_tokens=usage.get("cachedInputTokens"),
                    reasoning_output_tokens=usage.get("reasoningOutputTokens"),
                    total_tokens=total,
                    cost_usd=cost_usd,
                    cost_status=cost_status,
                )
                counted = billable if billable is not None else total
                if token_ceiling is not None and isinstance(counted, int) and counted > token_ceiling:
                    state.limit_error = AnnotationJobErrorV1(
                        code=AnnotationJobErrorCode.TOKEN_LIMIT_EXCEEDED,
                        message=f"turn used {counted} billable tokens ({total} total incl. cached), ceiling {token_ceiling} (tokens/cost bound)",
                    )
                    interrupt()
                elif cost_usd is not None and limits.max_cost_usd is not None and cost_usd > limits.max_cost_usd:
                    # Cached input is priced but not billable-counted, so the
                    # dollar ceiling is enforced from priced usage as well.
                    state.limit_error = AnnotationJobErrorV1(
                        code=AnnotationJobErrorCode.COST_LIMIT_EXCEEDED,
                        message=f"turn cost ${cost_usd:.6f} at the pinned price for {model}, ceiling ${limits.max_cost_usd:.6f}",
                    )
                    interrupt()
                return
            if method == "turn/completed":
                turn = params.get("turn") or {}
                if turn.get("id") in {None, state.turn_id}:
                    state.turn_status = str(turn.get("status") or "")
                    turn_error = turn.get("error")
                    if isinstance(turn_error, dict):
                        state.turn_error = str(turn_error.get("message") or "")
                    record("turn_completed", status=state.turn_status)
                return
            if method == "error":
                err = params.get("error") or {}
                state.server_errors.append(str(err.get("message") or "error"))
                record("server_error", message=str(err.get("message") or "")[:200], will_retry=params.get("willRetry"))
                return
            if method.startswith("item/reasoning/"):
                return  # never captured by policy
            record("notification", method=method)

        def interrupt() -> None:
            if state.thread_id and state.turn_id:
                try:
                    transport.send({"jsonrpc": "2.0", "id": f"interrupt-{state.turn_id}", "method": "turn/interrupt", "params": {"threadId": state.thread_id, "turnId": state.turn_id}})
                    record("interrupt_sent")
                except TransportClosed:
                    pass

        def call(method: str, params: dict[str, Any]) -> dict[str, Any]:
            nonlocal next_id
            next_id += 1
            request_id = next_id
            pending[request_id] = method
            transport.send({"jsonrpc": "2.0", "id": request_id, "method": method, "params": params})
            while True:
                wait = remaining()
                if wait <= 0:
                    raise TimeoutError(method)
                message = transport.receive(min(wait, self.poll_seconds))
                if message is None:
                    continue
                if message.get("id") == request_id and "method" not in message:
                    pending.pop(request_id, None)
                    if "error" in message:
                        err = message["error"] or {}
                        raise RuntimeError(f"{method} failed: {err.get('message') or err}")
                    result = message.get("result")
                    return result if isinstance(result, dict) else {}
                dispatch(message)

        def dispatch(message: dict[str, Any]) -> None:
            if "method" in message and "id" in message:
                handle_server_request(message)
            elif "method" in message:
                handle_notification(message)
            elif "id" in message:
                # Late response to a request we no longer wait on (e.g. interrupt).
                record("late_response", id=str(message.get("id")))

        try:
            transport.start()
            call("initialize", {"clientInfo": {"name": CLIENT_NAME, "title": "Synth trace annotation", "version": CLIENT_VERSION}, "capabilities": {"experimentalApi": True}})
            transport.send({"jsonrpc": "2.0", "method": "initialized", "params": {}})
            thread_params: dict[str, Any] = {
                "cwd": str(context.workspace_dir),
                "approvalPolicy": "never",
                "sandbox": "read-only",
                "ephemeral": True,
                "dynamicTools": tools.specs(),
                "developerInstructions": (
                    "You are a read-only trace annotator. Use only the trace_* tools. "
                    "Never run commands, edit files, or browse. Reply once with the JSON object requested."
                ),
            }
            if model:
                thread_params["model"] = model
            started_thread = call("thread/start", thread_params)
            state.thread_id = str((started_thread.get("thread") or {}).get("id") or "")
            if not state.thread_id:
                raise RuntimeError("thread/start returned no thread id")
            turn_params: dict[str, Any] = {
                "threadId": state.thread_id,
                "input": [{"type": "text", "text": context.instructions_text}],
                "outputSchema": STRICT_PROPOSAL_JSON_SCHEMA,
                "approvalPolicy": "never",
                "sandboxPolicy": {"type": "readOnly", "networkAccess": False},
            }
            if model:
                turn_params["model"] = model
            if effort:
                turn_params["effort"] = effort
            started_turn = call("turn/start", turn_params)
            state.turn_id = str((started_turn.get("turn") or {}).get("id") or "")
            while state.turn_status is None:
                if context.cancel_requested():
                    error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.CANCELLED, message="cancelled while running")
                    interrupt()
                    break
                wait = remaining()
                if wait <= 0:
                    error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.TIMEOUT, message=f"annotator exceeded {limits.timeout_seconds}s")
                    interrupt()
                    break
                message = transport.receive(min(wait, self.poll_seconds))
                if message is None:
                    continue
                dispatch(message)
            if error is None and state.limit_error is not None:
                error = state.limit_error
            if error is None and state.turn_status not in {"completed"}:
                error = AnnotationJobErrorV1(
                    code=AnnotationJobErrorCode.TRANSPORT_DISCONNECTED if state.turn_status is None else AnnotationJobErrorCode.INTERNAL,
                    message=f"turn ended with status {state.turn_status!r}: {state.turn_error or '; '.join(state.server_errors) or 'no detail'}",
                )
        except TransportClosed as closed:
            error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.TRANSPORT_DISCONNECTED, message=str(closed))
        except TimeoutError as timed_out:
            error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.TIMEOUT, message=f"timed out waiting for {timed_out}")
        except RuntimeError as failed:
            error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.RUNNER_UNAVAILABLE, message=str(failed))
        finally:
            try:
                transport.close()
            except Exception:  # noqa: BLE001
                pass

        proposal: Any = None
        if error is None:
            if state.final_text is None:
                error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.NO_STRUCTURED_OUTPUT, message="turn completed without a final agent message")
            else:
                try:
                    proposal = normalize_strict_proposal(json.loads(state.final_text))
                except ValueError as bad:
                    error = AnnotationJobErrorV1(code=AnnotationJobErrorCode.MALFORMED_OUTPUT, message=f"final message is not JSON: {bad}")
        ended = utc_now()
        usage = AnnotationJobUsageV1(
            tool_calls=len(tools.calls),
            tool_bytes=tools.total_bytes,
            input_tokens=state.usage.input_tokens,
            output_tokens=state.usage.output_tokens,
            cached_input_tokens=state.usage.cached_input_tokens,
            reasoning_output_tokens=state.usage.reasoning_output_tokens,
            total_tokens=state.usage.total_tokens,
            cost_usd=state.usage.cost_usd,
            cost_status=state.usage.cost_status,
            wall_time_seconds=time.monotonic() - clock,
        )
        capture = ExecutionCapture(
            started_at=started,
            ended_at=ended,
            instructions_digest=context.instructions_digest,
            tool_calls=tuple(tools.calls),
            final_output=proposal if isinstance(proposal, dict) else None,
            final_output_text=None if isinstance(proposal, dict) else state.final_text,
            usage=usage,
            runner_kind=self.kind,
            model=model,
            reasoning_effort=effort,
            transport_events=tuple(state.events),
            error=error.message if error else None,
            provider_thread_id=state.thread_id,
            provider_turn_id=state.turn_id,
        )
        producer = producer_for(
            context.entry.definition,
            kind=ProducerKind.AGENTIC,
            name="codex_app_server",
            version=RUNNER_VERSION,
            model=model,
            config_digest=context.entry.program.content_digest,
        )
        return RunOutcome(proposal=proposal, capture=capture, error=error, producer=producer)


# -- scripted fake ------------------------------------------------------------------------

AgentScript = Callable[[], "Iterator[tuple[str, dict[str, Any]]]"]


class ScriptedAppServer:
    """In-process fake of the app-server wire protocol for contract tests.

    ``agent`` is a generator factory. Each ``yield (tool, arguments)`` becomes an
    ``item/tool/call`` server request; the tool's text response is sent back into
    the generator. Its return value is the final ``agentMessage`` text. Behaviour
    knobs reproduce the failure modes the runner must survive.
    """

    def __init__(
        self,
        agent: AgentScript,
        *,
        final_status: str = "completed",
        omit_final_message: bool = False,
        disconnect_after_calls: int | None = None,
        hang_after_calls: int | None = None,
        token_usage: dict[str, int] | None = None,
        reject_thread_start: bool = False,
    ) -> None:
        self.agent = agent
        self.final_status = final_status
        self.omit_final_message = omit_final_message
        self.disconnect_after_calls = disconnect_after_calls
        self.hang_after_calls = hang_after_calls
        self.token_usage = token_usage
        self.reject_thread_start = reject_thread_start
        self.sent: list[dict[str, Any]] = []
        self._outbox: list[dict[str, Any]] = []
        self._gen: Iterator[tuple[str, dict[str, Any]]] | None = None
        self._pending_call_id: str | None = None
        self._calls = 0
        self._closed = False
        self._hung = False
        self.thread_id = "thread-fake"
        self.turn_id = "turn-fake"
        self.interrupted = False
        self.approval_decisions: list[str | None] = []

    def start(self) -> None:
        return None

    def _advance(self, feed: Any = None) -> None:
        assert self._gen is not None
        try:
            tool, arguments = self._gen.send(feed) if feed is not None else next(self._gen)
        except StopIteration as done:
            final = done.value
            if self.token_usage:
                self._outbox.append({"jsonrpc": "2.0", "method": "thread/tokenUsage/updated", "params": {"threadId": self.thread_id, "turnId": self.turn_id, "tokenUsage": {"total": self.token_usage, "last": self.token_usage}}})
            if not self.omit_final_message and final is not None:
                self._outbox.append({"jsonrpc": "2.0", "method": "item/completed", "params": {"threadId": self.thread_id, "turnId": self.turn_id, "completedAtMs": 0, "item": {"type": "agentMessage", "id": "item-final", "text": final}}})
            self._outbox.append({"jsonrpc": "2.0", "method": "turn/completed", "params": {"threadId": self.thread_id, "turn": {"id": self.turn_id, "status": self.final_status, "items": [], "error": {"message": "scripted failure"} if self.final_status == "failed" else None}}})
            return
        self._calls += 1
        if tool == "__request_approval__":
            self._pending_call_id = f"approval-{self._calls}"
            self._outbox.append({"jsonrpc": "2.0", "id": self._pending_call_id, "method": "item/commandExecution/requestApproval", "params": {"threadId": self.thread_id, "turnId": self.turn_id, "itemId": f"item-{self._calls}", "command": arguments.get("command", "rm -rf /"), "cwd": "/"}})
            return
        if self.disconnect_after_calls is not None and self._calls > self.disconnect_after_calls:
            self._closed = True
            return
        if self.hang_after_calls is not None and self._calls > self.hang_after_calls:
            self._hung = True
            return
        self._pending_call_id = f"call-{self._calls}"
        self._outbox.append({"jsonrpc": "2.0", "id": self._pending_call_id, "method": "item/tool/call", "params": {"threadId": self.thread_id, "turnId": self.turn_id, "callId": self._pending_call_id, "tool": tool, "arguments": arguments}})

    def send(self, message: dict[str, Any]) -> None:
        if self._closed:
            raise TransportClosed("scripted server closed")
        self.sent.append(message)
        method = message.get("method")
        request_id = message.get("id")
        if method == "initialize":
            self._outbox.append({"jsonrpc": "2.0", "id": request_id, "result": {"userAgent": "scripted"}})
        elif method == "initialized":
            return
        elif method == "thread/start":
            if self.reject_thread_start:
                self._outbox.append({"jsonrpc": "2.0", "id": request_id, "error": {"code": -1, "message": "scripted thread/start rejection"}})
            else:
                self._outbox.append({"jsonrpc": "2.0", "id": request_id, "result": {"thread": {"id": self.thread_id}, "model": message.get("params", {}).get("model") or "scripted", "modelProvider": "scripted", "approvalPolicy": "never", "cwd": message.get("params", {}).get("cwd"), "sandbox": "read-only"}})
        elif method == "turn/start":
            self._outbox.append({"jsonrpc": "2.0", "id": request_id, "result": {"turn": {"id": self.turn_id, "status": "inProgress", "items": []}}})
            self._gen = self.agent()
            self._advance()
        elif method == "turn/interrupt":
            self.interrupted = True
            self._outbox.append({"jsonrpc": "2.0", "id": request_id, "result": {}})
            self._outbox.append({"jsonrpc": "2.0", "method": "turn/completed", "params": {"threadId": self.thread_id, "turn": {"id": self.turn_id, "status": "interrupted", "items": []}}})
        elif method is None and request_id == self._pending_call_id and str(request_id).startswith("approval-"):
            self._pending_call_id = None
            self.approval_decisions.append((message.get("result") or {}).get("decision"))
            self._advance({"decision": (message.get("result") or {}).get("decision")})
        elif method is None and request_id == self._pending_call_id:
            result = message.get("result") or {}
            items = result.get("contentItems") or []
            text = items[0].get("text") if items else ""
            self._pending_call_id = None
            if result.get("success") is False:
                # A declined/limited tool result still reaches the agent; scripts may keep going.
                self._advance({"error": text})
            else:
                try:
                    self._advance(json.loads(text))
                except ValueError:
                    self._advance({"raw": text})
        else:
            self._outbox.append({"jsonrpc": "2.0", "id": request_id, "result": {}})

    def receive(self, timeout: float) -> dict[str, Any] | None:
        if self._closed:
            raise TransportClosed("scripted server closed")
        if self._outbox:
            return self._outbox.pop(0)
        if self._hung:
            time.sleep(min(timeout, 0.01))
            return None
        time.sleep(min(timeout, 0.005))
        return None

    def close(self) -> None:
        self._closed = True


__all__ = [
    "AppServerTransport",
    "CodexAppServerRunner",
    "ScriptedAppServer",
    "StdioAppServerTransport",
    "TransportClosed",
    "minimal_codex_config",
]
